# site settings
title: ADVANCED WAR UN
subtitle: 
email: matt.miller@uci.edu
description: A turn-based grid strategy game
baseurl: "/game-market.github.io" # "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://sodakang.github.io" # the base hostname & protocol for your site
author:
street_address: School of Information and Computer Sciences<br /> University of California, Irvine<br />  6210 Donald Bren Hall
city: Irvine
state: CA
zip_code: 92697-3425
country: United States of America
phone: (949) 824-5011

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url: https://www.facebook.com
github_url: https://github.com/freeyy/cs113
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
